"""
config.py
---------
Central place for settings, file paths, and secrets.

Every other pipeline file imports paths and settings from here instead of
hard-coding them. If a folder moves, this is the only file that changes.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# The project root is one folder above this "pipeline" folder.
PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Load secrets and settings from the .env file at the project root.
load_dotenv(PROJECT_ROOT / ".env")

# --- Secrets / settings coming from .env ---
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
PIPELINE_PORT = int(os.getenv("PIPELINE_PORT", "8001"))
SERVER_PORT = int(os.getenv("SERVER_PORT", "4000"))
SERVER_URL = f"http://localhost:{SERVER_PORT}"

# --- Input files ---
ZIP_PATH = PROJECT_ROOT / "categorizations.zip"
SYSTEM_PROMPT_PATH = PROJECT_ROOT / "docs" / "ergode_email_system_prompt.md"

# --- Output folders (generated by the pipeline, safe to delete/regenerate) ---
PARSED_THREADS_DIR = PROJECT_ROOT / "data" / "parsed_threads"
REPORTS_DIR = PROJECT_ROOT / "data" / "reports"

# Make sure the output folders exist before anything tries to write to them.
PARSED_THREADS_DIR.mkdir(parents=True, exist_ok=True)
REPORTS_DIR.mkdir(parents=True, exist_ok=True)


def require_openai_key() -> None:
    """Stop early with a clear message if no API key is configured yet."""
    if not OPENAI_API_KEY:
        raise RuntimeError(
            "OPENAI_API_KEY is not set. Copy .env.example to .env and add your key."
        )
